version: "3.8"

services:
  frontend:
    build:
      context: .  # Root directory (docker-compose.yml is here)
      dockerfile: client/Dockerfile  # Path to the frontend Dockerfile
    ports:
      - "3000:80"  # Map frontend port 3000 to 80 on the container
    networks:
      - app-network

  backend:
    build:
      context: .  # Root directory (docker-compose.yml is here)
      dockerfile: server/Dockerfile  # Path to the backend Dockerfile
    ports:
      - "8000:8000"  # Map backend port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
